[package]
name = "gauss-render"
version = "0.1.0"
edition = "2024"

[dependencies]
nalgebra = { version = "0.32", features = ["serde-serialize"] }
image = "0.24"
rayon = "1.7"
rand = "0.8"
serde = { version = "1.0", features = ["derive"] }
